// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace SceneObjectsSDK
{
	public class SceneManager : MonoBehaviour {
		
		// Use this for initialization
		IEnumerator Start () {
			WWW sceneObjects = new WWW ("http://localhost:3000/scene_objects.json");

			yield return sceneObjects;
			
			if (sceneObjects.error != null) {
				Debug.Log("ERROR downloading scene objects:" + sceneObjects.error);
			} else {
				Debug.Log("Successfully loaded scene objects" + sceneObjects.data);
				
				CreateSceneObjects(sceneObjects.data);
			}
		}
		
		void CreateSceneObjects (string jsonString) {
			JsonData jsonSceneObjects = JsonMapper.ToObject (jsonString);
			for (int i = 0; i < jsonSceneObjects.Count; i++) {
				JsonData jsonSceneObject = jsonSceneObjects[i];
				Debug.Log (jsonSceneObject);
				StartCoroutine(CreateSceneObject(sceneObject));
			}
		}
		
		IEnumerator CreateSceneObject (JsonData jsonSceneObject) {
			Debug.Log ("Create sceneObject with texture URL: " + jsonSceneObject["texture_url"]);
			WWW sceneObjectTextureImage = new WWW ((string)jsonSceneObject["texture_url"]);
			yield return sceneObjectTextureImage;
			Debug.Log (sceneObjectTextureImage.size);
			if (sceneObjectTextureImage.error != null) {
				Debug.Log ("ERROR downloading texture image:" + sceneObjectTextureImage.error);
			} else {
				int width = sceneObjectTextureImage.texture.width;
				int height = sceneObjectTextureImage.texture.height;
				float scaleX = (float)width / height;
				float scaleY = (float)height / width;
			}

			//spawn object
			GameObject sceneObject = new GameObject((string)jsonSceneObject["name"]);

			// Add components
			Rigidbody rigidbody = sceneObject.AddComponent<Rigidbody>();
			MeshFilter meshFilter = sceneObject.AddComponent<MeshFilter>();
			MeshRenderer renderer = sceneObject.AddComponent<MeshRenderer>();

			Debug.Log(rigidbody);
			Debug.Log(meshFilter);
			Debug.Log(renderer);

			if (jsonSceneObject["kind"] == "Cube") {
				sceneObject.AddComponent<BoxCollider>();
			} else if (jsonSceneObject["kind"] == "Sphere") {
				sceneObject.AddComponent<SphereCollider>();
			}
			
			sceneObject.transform.localScale = new Vector3(jsonSceneObject["scale"]);
			sceneObject.transform.localEulerAngle = new Vector3(jsonSceneObject["rotation"]);
			sceneObject.transform.position = new Vector3(jsonSceneObject["position"]);
		}
		
		// Update is called once per frame
		void Update () {
		}
	}
}

